### PR TITLE
Re-instrument `Run` and `Grade` buttons

### LINKED ISSUE #1007: [Analytics] Run Button Instrumentation no longer working
### Steps to reproduce the problem

1. Go to this [page](https://learn.qiskit.org/course/introduction/the-atoms-of-computation) *note this is occurring for all pages featuring the run button
2. Click on the Run button icon
3. Check the segment chrome extension, should show "CTA Clicked" for run button but not showing

### What is the current behavior?

When you click the run button, segment is not tracking this event

### What is the expected behavior?

Segment should be tracking this event

### Screenshots (optional but very helpful)

If applicable, please add screenshots or video captures to help explain the problem.

Screen Shot 2022-05-16 at 11 33 22 AM

### PR DESCRIPTION
**Pull request by techtolentino**
## Changes

Fixes #1007 
Co-authored-by: @korgan00 🙌 

## Implementation details

- instrumented the `Run` and `Grade` button, per each `CodeExercise` component
- each code exercise will have a numbered `id`
- we pass the `id`, as part of the location parameter, into the Segment `trackClickEvent()` 

## How to read this PR

- review code implementation
- test in branch locally (unfortunately, we don't have Cookies settings in branch previews)
- or review screenshot provided below

## Screenshots

https://user-images.githubusercontent.com/6276074/174325268-c88d2ce9-fd63-462a-bc3c-9de1853eed82.mov

### CODE REVIEW

File: frontend/vue/components/CodeExercise/CodeEditor.vue [hunk 1]
```diff
@@ -38,7 +38,7 @@ import CodeArea from './CodeArea.vue'
 import 'carbon-web-components/es/components/notification/toast-notification'
 
 export default defineComponent({
-  name: 'CodeExercise',
+  name: 'CodeEditor',
```
Comment (korgan00) [inline frontend/vue/components/CodeExercise/CodeEditor.vue:41]: thanks! :)

File: frontend/vue/components/CodeExercise/CodeExercise.vue [hunk 2]
```diff
@@ -84,16 +95,21 @@ export default defineComponent({
     const initialCodeElement = slotWrapper.getElementsByTagName('pre')[0]
     this.code = initialCodeElement?.textContent?.trim() ?? ''
     this.initialCode = this.code
+    this.id = lastId++
   },
   methods: {
     run () {
       const codeOutput: any = this.$refs.output
+      const pageTitle = document.querySelector('.page-title')?.textContent
```
Comment (korgan00) [inline frontend/vue/components/CodeExercise/CodeExercise.vue:103]: I think that the route name is better since we have several `Introduction` units and it the name will change with the language.

File: frontend/vue/components/CodeExercise/CodeExercise.vue [hunk 3]
```diff
@@ -84,16 +95,21 @@ export default defineComponent({
...
+
       codeOutput.requestExecute(this.code)
+      window.textbook.trackClickEvent('Run', `Code cell #${this.id}, ${pageTitle}`)
     },
     grade () {
       const codeOutput: any = this.$refs.output
       const wrappedCode: string = this.graderImport + '\n' + this.code + '\n' + this.graderFunction
       codeOutput.requestExecute(wrappedCode)
+      window.textbook.trackClickEvent('Grade', `Code cell #${this.id}, ${this.goal}`)
```
Comment (korgan00) [inline frontend/vue/components/CodeExercise/CodeExercise.vue:112]: Here we should add the unit name too.

File: frontend/vue/components/CodeExercise/CodeExercise.vue [hunk 4]
```diff
@@ -41,6 +41,16 @@ import CodeEditor from './CodeEditor.vue'
 import ExerciseActionsBar from './ExerciseActionsBar.vue'
 import CodeOutput from './CodeOutput.vue'
 
+declare global {
+  interface Window {
+    textbook: any,
+    textbookAnalytics: any
+  }
+}
```
Comment (korgan00) [inline frontend/vue/components/CodeExercise/CodeExercise.vue:49]:
```suggestion
declare global {
  interface Window {
    textbook: any
  }
}
```

**Review by korgan00 — CHANGES_REQUESTED** [review]

**Review by korgan00 — APPROVED** [review]
